name: sunbeam
base: core20
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  Sunbeam aims to provide a scalable, simple to deploy OpenStack solution.
version: yoga

confinement: strict
grade: devel

apps:
  sunbeam:
    command: bin/sunbeam
    plugs:
      - home
      - juju-client-observe
      - network
      - network-bind
      - ssh-public-keys
      - snapd-control

parts:
  sunbeam:
    plugin: python
    source: .
    build-packages:
      - git
    requirements:
      - requirements.txt
    override-build: |
      snapcraftctl build
      snap-helpers write-hooks

  bundles:
    plugin: dump
    source: bundles/

  curl:
    plugin: nil
    stage-packages:
      - curl

plugs:
  peers:
    interface: content
    content: microk8s
    # Note (wolsen): if we specify the default provider here, then snapd will
    # attempt to install it and make sure that it is available. I'm not sure
    # that we want this always (think compute-only node).
    default-provider: microk8s
    target: $SNAP_DATA/microk8s

  juju:
    interface: content
    content: juju
    # Note (wolsen): if we specify the default provider here, then snapd will
    # attempt to install it automatically and make sure that it is available.
    # This requires that the snap is available as a non-classic snap in order
    # to do this. We may need to bundle in the version of Juju.
    #default-provider: 3.0/beta
    target: $SNAP/juju
