name: microstack
base: core20
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  Microstack aims to provide a scalable, simple to deploy OpenStack solution.
version: xena

confinement: strict
grade: devel

apps:
  microstack:
    command: bin/microstack
    plugs:
      - dot-local-share-juju
      - home
      - network
      - network-bind
      - ssh-public-keys

parts:
  microstack:
    plugin: python
    source: .
    build-packages:
      - git
    requirements:
      - requirements.txt
    override-build: |
      snapcraftctl build
      snap-helpers write-hooks

  bundles:
    plugin: dump
    source: bundles/

plugs:
  # Needed for juju client to autodiscover microk8s cloud
  microk8s:
    interface: content
    content: microk8s
    target: $SNAP_DATA/microk8s

  juju-bin:
    interface: content
    content: juju
    target: $SNAP/juju

  hypervisor-config:
    interface: content
    content: openstack-hypervisor
    target: $SNAP_DATA

  dot-local-share-juju:
    interface: personal-files
    write:
      - $HOME/.local/share/juju
