name: microstack
base: core20
summary: Dead simple OpenStack installation
license: Apache-2.0
description: |
  Microstack aims to provide a scalable, simple to deploy OpenStack solution.
version: xena

confinement: strict
grade: devel

apps:
  microstack:
    command: bin/microstack
    plugs:
      - home
      - juju-client-observe
      - network
      - network-bind
      - ssh-public-keys

parts:
  microstack:
    plugin: python
    source: .
    build-packages:
      - git
    requirements:
      - requirements.txt
    override-build: |
      snapcraftctl build
      snap-helpers write-hooks

  bundles:
    plugin: dump
    source: bundles/

plugs:
  peers:
    interface: content
    content: microk8s
    # Note (wolsen): if we specify the default provider here, then snapd will
    # attempt to install it and make sure that it is available. I'm not sure
    # that we want this always (think compute-only node).
    #default-provider: microk8s/1.25-strict
    target: $SNAP_DATA/microk8s

  juju:
    interface: content
    content: juju
    # Note (wolsen): if we specify the default provider here, then snapd will
    # attempt to install it automatically and make sure that it is available.
    # This requires that the snap is available as a non-classic snap in order
    # to do this. We may need to bundle in the version of Juju.
    #default-provider: juju/3.0
    target: $SNAP/juju

  hypervisor-config:
    interface: content
    content: openstack-hypervisor
    target: $SNAP_COMMON
